blank_issues_enabled: true
contact_links:
  - name: 🤔 Ask a Question
    url: https://github.com/somespecialone/petry-action-test/discussions/new?category=q-a
    about: Please ask and answer questions here.
