name: Publish

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache: poetry
      - run: poetry install

      - name: Build distribution package
        run: poetry build

      - uses: actions/upload-artifact@v3
        with:
          name: lib-dist
          path: dist
