name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      dist-file: ${{ steps.pack.outputs.dist-file }}
    steps:
      - uses: actions/checkout@v4
      - name: Pack distribution package
        id: pack
        working-directory: lib
        run: |
          echo "dist-file=$(find -name '*.tgz')" >> $GITHUB_OUTPUT
          cp *.tgz ..

      - uses: actions/upload-artifact@v3
        with:
          name: package-dist
          path: ${{ steps.pack.outputs.dist-file }}
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: package-dist

      - run: |
          ls
          find -name '*.tgz'
          echo "${{ needs.build.outputs.dist-file }}"
          if test -f "${{ needs.build.outputs.dist-file }}"; then echo "tar exists."; fi
