name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create & publish release
        uses: softprops/action-gh-release@v0.1.15
        with:
          body_path: CHANGELOG.md
          generate_release_notes: true
